<a href="https://colab.research.google.com/github/AKASH-GO/AKASH-GO/blob/main/akashrajacolab-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("Tensorflow version:",tf.__version__)


Tensorflow version: 2.8.2


In [ ]:
import tensorflow as tf

x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

tf.multiply(x1, x2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 5, 12, 21, 32], dtype=int32)>

In [ ]:
import tensorflow as tf

x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

tf.add(x1, x2)

In [ ]:
import tensorflow as tf

x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

tf.subtract(x1, x2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-4, -4, -4, -4], dtype=int32)>

In [ ]:
import tensorflow as tf

x1 = tf.constant([1,2,3,4])
x2 = tf.constant([5,6,7,8])

tf.divide(x1, x2)

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 0.5       ])>

In [ ]:
#binary + operator
x=tf.convert_to_tensor([1,2,3,4,5])
y=tf.convert_to_tensor(1)
x+y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#binary * operator
x=tf.convert_to_tensor([1,2,3,4,5])
y=tf.convert_to_tensor(4)
x*y

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 4,  8, 12, 16, 20], dtype=int32)>

In [ ]:
#creating a matrix
matrix=tf.constant([[1,2],[3,4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
matrix=tf.constant([[1,2],[3,4],[3,5],[3,6],[7,4],[9,4],[10,4]])
print(matrix)
print('the number of dimension of a matrix is:\ ' +str(matrix.ndim )

SyntaxError: ignored

In [ ]:
d=tf.constant(([[1,2],[3,4],[5,6]]))
print (d.get_shape())
e=tf.ones(d.shape[1])

(3, 2)


In [ ]:
e=tf.ones(d.shape[0])
print (e.get_shape())

(3,)
